plugins:
  - rubocop-factory_bot
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'node_modules/**/*'

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 100

Metrics/AbcSize:
  Max: 20

Style/FrozenStringLiteralComment:
  Enabled: true